### PR TITLE
Updates in readme and pbs usage

### PR DESCRIPTION
**Pull request by alejandrodob**

### CODE REVIEW

**Comment by therealmarv** [comment]
the things added look ok, but many files removed. Is this intended?

**Comment by therealmarv** [comment]
:cake: for the changes. Only want to make sure not too much deleted ;)

**Comment by alejandrodob** [comment]
@therealmarv it is, because we are now using pbs to create the project and update it, add tasks, etc.
app.json has been substituted by project.json. createTasks.py was not even working, as it used a deprecated pybossa-client API but no version was specified on the requirements.txt for that library. Now pbs handles that anyway. The long description expected by pbs is markdown, so I just removed the html (which we no longer support in PyBossa anyway) and finally the `__init__.py` was no longer needed.

**Comment by alejandrodob** [comment]
Also, check this other project for similar changes ;) https://github.com/PyBossa/app-flickrperson

**Pull request merged**
